server.port=${PORT:8080}
spring.application.name=chatter

spring.mongodb.uri=${DB_URI}
spring.mongodb.database=${DB_DATABASE}

#GitHub imagerep
github.username=Sakthivel1107
github.repo=image-storage
github.branch=main
github.token=${GITHUB_TOKEN}

jwt.secret.key=${SECRET_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

resend_api_key=${RESEND_API_KEY}

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

rapid_api_key=${RAPID_API_KEY}
